# do we need this ???
#- name: create and copy the post-autoyast file of the machine
#  template:
#    src: debian/post-preseed.sh
#    dest: "{{ webpath }}{{ inventory_hostname }}.sh"
#    owner: nginx
#    group: nginx
#    mode: 0666
#    setype: httpd_sys_content_t
#  delegate_to: "{{ webserver }}"

- name: create and copy the autoyast file of the machine
  template:
    src: "opensuse/autoyast.cfg"
    dest: "{{virtualfilespath }}{{ inventory_hostname }}.cfg"
  delegate_to: "{{ hyper }}"

- name: create and copy the install script
  template:
    src: "common/install-vm.sh"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
    owner: root
    group: root
    mode: 0770
  delegate_to: "{{ hyper }}"

- name: execute install script
  command: "/bin/bash {{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
  delegate_to: "{{ hyper }}"
  register: createdvm

- name: wait for vm to install
  pause: minutes={{ vmwaittime }}
  connection: local
