- name: get webserver variables
  include_vars: webserver.yml

- name: create and copy the autoinstall file of the machine
  template:
    src: openbsd/autoinstall.conf
    dest: "{{ virtualfilespath }}autoinstall.conf"
    mode: 0444
  delegate_to: "{{ hyper }}"

- name: copy templated install script
  template:
    src: openbsd/install-vm.sh
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
    owner: root
    group: root
    mode: 0770
  delegate_to: "{{ hyper }}"

- name: copy autoinstall template
  template:
    src: openbsd/autoinstall.conf
    dest: "{{ virtualfilespath }}/autoinstall.conf"
    owner: root
    group: root
    mode: 0660
  delegate_to: "{{ hyper }}"

- name: install script dependencies
  yum:
    pkg: "{{ item }}"
    dest: "{{ webpath }}/{{ inventory_hostname }}.conf"
    owner: "{{ webuser }}"
    group: "{{ webuser}}"
    mode: 0664
  delegate_to: "{{ webserver }}"

- name: install script dependencies
  yum:
    pkg: expect dvd+rw-tools
    state: latest
  delegate_to: "{{ hyper }}"

#- name: execute install script
#  shell: "{{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
#  args:
#    executable: /bin/bash
#  delegate_to: "{{ hyper }}"
#  #ignore_errors: yes
#  #register: createdvm

- name: wait for installation to complete
  pause:
    minutes: "{{ vmwaittime }}"
  connection: local
  #only_if: "{{ createdvm.stdout_lines }} == ''"

- name: copy min-ram script
  template:
    src: "templates/common/minram.sh"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-minram.sh"
    owner: root
    group: root
    mode: 0770
  delegate_to: "{{ hyper }}"
  when: ramsize < minram

- name: execute min-ram script
  raw: "{{ virtualfilespath }}{{ inventory_hostname }}-minram.sh"
  delegate_to: "{{ hyper }}"
  when: ramsize < minram

- name: start the vm
  virt:
    guest: "{{ inventory_hostname }}"
    command: start
  delegate_to: "{{ hyper }}"
  ignore_errors: yes

#- name: remove all installation files
#  file:
#    path: "{{ item }}"
#    state: absent
#  delegate_to: "{{ hyper }}"
#  with_items:
#    - "{{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
#    - "{{ virtualfilespath }}{{ isofile }}"
#    - "{{ virtualfilespath }}boot.conf"
#    - "{{ virtualfilespath }}random.seed"
#    - "{{ virtualfilespath }}{{ inventory_hostname }}-minram.sh"

#- local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} delay=5 state=started timeout=300
#  sudo: no
